apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main,master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: frontend-application
    appstudio.openshift.io/component: testsample-go
    build.appstudio.openshift.io/component: testsample-go
    pipelines.appstudio.openshift.io/type: build
  name: testsample-go-on-pull-request
  namespace: karthik-jk
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-appstudio/user-workload:on-pr-{{revision}}
  - name: dockerfile
    value: https://raw.githubusercontent.com/karthikjeeyar/testsample-go/main/docker/Dockerfile
  pipelineRef:
    bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
    name: docker-build
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: appstudio
    subPath: testsample-go-on-pull-request-{{revision}}
status: {}
